import type { Product } from "../shop.types";

export const PRODUCTS: Product[] = [
  {
    id: "uva-bop",
    name: "Uva Highland BOP",
    region: "UVA",
    elevation: "1,610 M",
    price: 2400,
    weight: "100 G",
    notes: "Wintergreen · honey · woodsmoke",
    grade: "BOP — Broken Orange Pekoe",
    estate: "Pelmadulla, Eastern Slopes",
    flush: "June Quality (2025)",
    pairs: ["uva-fop", "uva-tin", "gift-mountain"],
  },
  {
    id: "nuwara-fop",
    name: "Nuwara Eliya FOP",
    region: "NUWARA ELIYA",
    elevation: "1,868 M",
    price: 2800,
    weight: "100 G",
    notes: "Jasmine · stone fruit · cool mineral",
    grade: "FOP — Flowery Orange Pekoe",
    estate: "Pedro Estate",
    flush: "March 2026",
  },
  {
    id: "dimbula-op",
    name: "Dimbula OP",
    region: "DIMBULA",
    elevation: "1,250 M",
    price: 2100,
    weight: "100 G",
    notes: "Citrus zest · rose · brisk",
    grade: "OP — Orange Pekoe",
    estate: "Lonach Estate",
    flush: "Western Quality",
  },
  {
    id: "ruhuna-pekoe",
    name: "Ruhuna Low-grown Pekoe",
    region: "RUHUNA",
    elevation: "240 M",
    price: 1900,
    weight: "100 G",
    notes: "Caramel · date · cocoa",
    grade: "PEKOE",
    estate: "Berubeula, Galle",
    flush: "Continuous",
  },
  {
    id: "kandy-bops",
    name: "Kandy BOPSF",
    region: "KANDY",
    elevation: "660 M",
    price: 1750,
    weight: "100 G",
    notes: "Malt · raisin · gentle tannin",
    grade: "BOPSF — Broken Orange Pekoe Sup. Fannings",
    estate: "Hewaheta",
    flush: "Mid-grown",
  },
  {
    id: "gift-mountain",
    name: "The Mountain Hamper",
    region: "GIFT SET",
    elevation: "FOUR TINS",
    price: 9800,
    weight: "400 G",
    notes: "One tin from each elevation",
    grade: "GIFT SET",
    estate: "Curated",
    flush: "Year-round",
  },
  {
    id: "infuser-clay",
    name: "Lansdowne Clay Pot",
    region: "ACCESSORY",
    elevation: "500 ML",
    price: 7200,
    weight: "1 PC",
    notes: "Hand-thrown stoneware, Sri Lankan kiln",
    grade: "ACCESSORY",
    estate: "Matale potters",
    flush: "—",
  },
  {
    id: "sub-monthly",
    name: "Monthly Tasting Subscription",
    region: "SUBSCRIPTION",
    elevation: "3 × 50G",
    price: 3400,
    weight: "MONTH",
    notes: "Three new single-origins each month",
    grade: "SUBSCRIPTION",
    estate: "Rotating",
    flush: "Year-round",
  },
];

export const getProductById = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);
